# Generated by Django 2.2.6 on 2019-10-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('image', models.ImageField(null=True, upload_to='images/taller/', verbose_name='Imagen')),
                ('phones', models.CharField(help_text='los teléfonos pueden ir separados por comas', max_length=100, null=True, verbose_name='Teléfonos')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
    ]
