# Generated by Django 2.2.6 on 2019-10-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.City', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='image',
            field=models.ImageField(null=True, upload_to='images/talleres/', verbose_name='Imagen'),
        ),
    ]
