# Generated by Django 2.2.6 on 2019-10-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_auto_20191004_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='location',
            field=models.CharField(null=True,max_length=200),
            preserve_default=False,
        ),
    ]
