# Generated by Django 2.2.6 on 2019-10-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_taller_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='location',
        ),
    ]
