# Generated by Django 2.2.6 on 2019-10-04 23:30

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_remove_taller_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='-25.3014877,-57.5804482', max_length=63, null=True),
        ),
    ]
