# Generated by Django 2.2.6 on 2019-10-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_taller_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='title',
        ),
        migrations.AddField(
            model_name='taller',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Descripcion Breve'),
        ),
        migrations.AddField(
            model_name='taller',
            name='large_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Larga'),
        ),
        migrations.AddField(
            model_name='taller',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='taller',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='taller',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
