# Generated by Django 2.2.6 on 2019-10-05 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_brand'),
        ('talleres', '0006_auto_20191005_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='Celular')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('document', models.CharField(max_length=100, null=True, verbose_name='Documento')),
                ('year', models.PositiveSmallIntegerField(null=True, verbose_name='Año')),
                ('car_km', models.PositiveIntegerField(null=True, verbose_name='Kilometraje')),
                ('license_plate', models.CharField(max_length=100, null=True, verbose_name='Número')),
                ('id_type', models.CharField(choices=[('CHAPA', 'Chapa'), ('CHASIS', 'Chasis')], max_length=100, null=True, verbose_name='Tipo de Identificación')),
                ('comment', models.TextField(null=True, verbose_name='Comentario')),
                ('date', models.DateField(null=True, verbose_name='Fecha')),
                ('time', models.TimeField(null=True, verbose_name='Hora')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Brand')),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='talleres.Taller')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
