# Generated by Django 2.2.6 on 2019-10-06 05:24

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0009_auto_20191005_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='email',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='phone',
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='-25.3014877,-57.5804482', max_length=63, null=True),
        ),
    ]
