# Generated by Django 2.2.6 on 2019-10-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0010_auto_20191006_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='talleres.ServiceType'),
        ),
        migrations.AlterField(
            model_name='service',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='talleres.Taller', verbose_name='Taller'),
        ),
    ]
