# Generated by Django 2.2.6 on 2019-10-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20191005_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/', verbose_name='Imagen'),
        ),
    ]
