# Generated by Django 2.2.6 on 2019-10-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='images/brands/', verbose_name='Imagen'),
        ),
    ]
