# Generated by Django 2.2.6 on 2019-10-06 03:14

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='-25.3014877,-57.5804482', max_length=63, null=True),
        ),
    ]
